name: Build

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl --fail http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube..."
          for i in {1..30}; do
            curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"' && break
            sleep 5
          done

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          host-url: http://localhost:9000
          token: ${{ secrets.SONAR_TOKEN }}
